[build]
command = "npm run build"
publish = ".next"
functions = "netlify/functions"

[[redirects]]
from = "/api/analyze"
to = "/.netlify/functions/analyze"
status = 200

[context.production.environment]
# Token da definire nel pannello Netlify → Site Settings → Environment Variables
HUGGINGFACE_TOKEN = ""

# Obbligatorio per evitare errori su build con plugin next obsoleti
NETLIFY_NEXT_PLUGIN_SKIP = "false"

[functions]
node_bundler = "esbuild"
